services:
  perforce:
    container_name: Perforce-Server
    hostname: perforce
    volumes:
      - /mnt/user/appdata/perforce-server/logs:/data/p4depot/logs
      - /mnt/user/Perforce/:/data
    ports:
      - "1666:1666"
    environment:
      - P4PORT=ssl:1666
      - P4SSLDIR=/data/p4depot/ssl
      - P4ROOT=/data/p4depot
      - P4USER=admin
      - P4USER=p4admin
      - P4PASSWD=pass12349ers!
    build:
      context: .
      dockerfile: Dockerfile
    #restart: unless-stopped  # Optional: Restart the container if it stops unexpectedly